services:
  mysql:
    image: mysql:8.0
    container_name: hogwarts-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hogwarts
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hogwarts-network

  app:
    build: .
    container_name: hogwarts-app
    ports:
      - "5001:5001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hogwarts
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hogwarts-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - app
    networks:
      - hogwarts-network

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./docker/grafana:/var/lib/grafana
    env_file:
      - ./docker/grafana/grafana-config.env
    ports:
      - 3000:3000
    networks:
      - hogwarts-network

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - hogwarts-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - hogwarts-network

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:

networks:
  hogwarts-network:
    driver: bridge